networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fdf1:f4a2:d53::/64
          gateway: fdf1:f4a2:d53::ffff
services:
  db:
    image: postgres:${POSTGRES_TAG:-latest}
    shm_size: 1gb
    ports: [6543:5432]
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_HOST_AUTH_METHOD: ${AUTH_METHOD:-trust}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 3s
      timeout: 3s
      retries: 5

  web:
    build: .
    image: concourse/concourse:local1
    command: web
    depends_on:
      db:
        condition: service_healthy
    ports: [8080:8080]
    networks:
      - default
    volumes:
    - .:/src
    - "./hack/keys:/concourse-keys"
    environment:
      CONCOURSE_SESSION_SIGNING_KEY: /concourse-keys/session_signing_key
      CONCOURSE_TSA_AUTHORIZED_KEYS: /concourse-keys/authorized_worker_keys
      CONCOURSE_TSA_HOST_KEY: /concourse-keys/tsa_host_key

      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: dev
      CONCOURSE_POSTGRES_PASSWORD: dev
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test,guest:guest
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_CLUSTER_NAME: dev
      CONCOURSE_ENABLE_PIPELINE_INSTANCES: "true"
      CONCOURSE_ENABLE_ACROSS_STEP: "true"
      CONCOURSE_ENABLE_CACHE_STREAMED_VOLUMES: "true"
      CONCOURSE_ENABLE_RESOURCE_CAUSALITY: "true"
      CONCOURSE_AUTH_DURATION: 10m
      CONCOURSE_GC_FAILED_GRACE_PERIOD: 1m
      # CONCOURSE_MAIN_TEAM_SAML_USER: user1@example.com
      CONCOURSE_MAIN_TEAM_SAML_GROUP: group2

      CONCOURSE_SAML_SSO_URL: http://localhost:8000/simplesaml/saml2/idp/SSOService.php
      CONCOURSE_SAML_ENTITY_ISSUER: concourse
      CONCOURSE_SAML_USERNAME_ATTR: email
      CONCOURSE_SAML_GROUPS_ATTR: eduPersonAffiliation
      CONCOURSE_SAML_SKIP_SSL_VALIDATION: "true"
      # still need to specify file even if we skip tls
      CONCOURSE_SAML_CA_CERT: /bin/sh

  saml:
    image: kristophjunge/test-saml-idp
    ports:
    - 8000:8080
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: concourse
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:8080/sky/issuer/callback

  worker:
    build: .
    image: concourse/concourse:local1
    command: worker
    privileged: true
    cgroup: host
    networks:
      - default
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    depends_on: [web]
    ports:
    - 7777:7777
    - 7788:7788
    volumes: ["./hack/keys:/concourse-keys"]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_RUNTIME: containerd

      CONCOURSE_TSA_PUBLIC_KEY: /concourse-keys/tsa_host_key.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: /concourse-keys/worker_key

      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_TSA_HOST: web:2222

      CONCOURSE_BIND_IP: 0.0.0.0
      CONCOURSE_BAGGAGECLAIM_BIND_IP: 0.0.0.0

      # avoid using loopbacks
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay

      # work with docker-compose's dns
      CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE: "true"
